name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: 'tests/e2e/**/*'
        env:
          CYPRESS_baseurl: http://localhost:8080/
      - name: Store screenshots for test run
        run: mkdir cypress/screenshots
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Store vedios for test run
        run: mkdir cypress/videos
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Build Project
        run: npm run build
      - name: Archive Dist Folder
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
